version: 2.1

orbs:
  github-cli: circleci/github-cli@2.4.0

executors:
  docker_lts:
    docker:
      - image: cimg/node:lts

jobs:
  auto_sync_prs:
    executor: docker_lts
    steps:
      - checkout
      - run:
          name: Install GitHub CLI
          command: |
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list
            sudo apt update
            sudo apt install gh
      - run:
          name: Authenticate GitHub CLI
          command: echo $GH_TOKEN | gh auth login --with-token
      - run:
          name: Auto sync prs
          command: scripts/auto_sync_prs.sh

  auto_bump:
    executor: docker_lts
    steps:
      - checkout
      - run:
          name: Auto bump version
          command: scripts/auto_bump.sh

workflows:
  build_and_test:
    jobs:
      - auto_sync_prs
      - auto_bump:
          filters:
            branches:
              ignore:
                - main
                - develop