name: github_actions_ci

on:
  pull_request:
    branches: [ "develop" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  GPR_USERNAME: ${{ secrets.GPR_USERNAME }}

jobs:
  auto_bump:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project sources
        uses: actions/checkout@v4

      - name: auto bump version if required
        run: ./auto_bump.sh