name: pull_request_ci

on:
#  pull_request:
#    branches: [ "develop" ]
  push:

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  contents: write # Allows to commit files

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
  GPR_KEY: ${{ secrets.GPR_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GIT_BRANCH: ${{ github.event.pull_request.head.ref }}
  GIT_OWNER: ${{ github.repository_owner }}
  GIT_REPO: ${{ github.event.repository.name }}

jobs:
  auto_bump:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project sources
        uses: actions/checkout@v4
        with:
          # Allow to access files in the Pull Request
          ref: ${{ github.event.pull_request.head.ref }}

      - name: auto bump version if required
        run: ./auto_bump.sh
