# Enable github action: https://github.com/willian-gama/kgp/settings/actions
name: push_ci

on:
  push:
    branches: [ "dev" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # Allows to push git tag

env:
  GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
  GPR_KEY: ${{ secrets.GPR_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  auto-sync-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Sync PRs with target branch
        run: ./scripts/auto_sync_prs.sh develop