name: push_ci

on:
  push:
    branches: [ "develop" ]

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  contents: write # Allows to commit files

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
  GPR_KEY: ${{ secrets.GPR_KEY }}

jobs:
  release_plugin:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project sources
        uses: actions/checkout@v4

      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: zulu # Supported distributions: https://github.com/actions/setup-java#supported-distributions
          java-version: 21

      # https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: include local.properties from secret variables
        run: scripts/include_local_properties.sh

      - name: run tests
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository