name: pull_request_ci

on:
  workflow_run:
    workflows: [ "pull_request_ci" ]
    types: [ "completed" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
  GPR_KEY: ${{ secrets.GPR_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GIT_BRANCH: ${{ github.event.pull_request.head.ref }}
  GIT_OWNER: ${{ github.repository_owner }}
  GIT_REPO: ${{ github.event.repository.name }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project sources
        uses: actions/checkout@v4

      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: zulu # Supported distributions: https://github.com/actions/setup-java#supported-distributions
          java-version: 21

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      # https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: include local.properties from secret variables
        run: scripts/include_local_properties.sh

      - name: run tests
        run: ./gradlew test
